[site]
base_url = "http://localhost:8000"
static_dir = "example/static"
templates_dir = "example/templates"
content_dir = "example/content"
archetypes_dir = "example/archetypes"
build_dir = "example/output"

[params]
title = "Marastatic Example"
description = "Single-file SSG."

[params.author]
name = "Someone"
email = "someone@something.com"
